/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    FileRegistry: {
      address: "0xEbdCf8DaE6E7962c38EBfE3c75BC75aA7F562357",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "field",
              type: "string",
            },
          ],
          name: "EmptyValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidContentHash",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotFileOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "FileDelisted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "FileRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldPayToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "PayToChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldPriceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "PriceChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "VisibilityChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PAYMENT_ASSET",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
          ],
          name: "computeFileId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "delistFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "getFile",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getFileCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getFiles",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem[]",
              name: "files",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "registerFile",
          outputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "setPayToAccountId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "setPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "setVisibility",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41351849,
      hederaContractId: "0.0.10858803",
    },
    Policy402: {
      address: "0xF28dD385aB3288f6c11423994968317dA4Be09B8",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "fileRegistryAddress",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "InvalidFileId",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidFileRegistry",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPayTo",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPaymentAsset",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPrice",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidServiceId",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidValidityWindow",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyAlreadyRevoked",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyVersionNotFound",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
          ],
          name: "PolicyRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "PolicyVersionCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "computeFileServiceId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "computePolicyHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
          ],
          name: "computePolicyId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "descriptor",
              type: "string",
            },
          ],
          name: "computeServiceId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "createVersion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "fileRegistry",
          outputs: [
            {
              internalType: "contract IFileRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
          ],
          name: "getCurrentPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "fileId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "currentVersion",
                  type: "uint256",
                },
              ],
              internalType: "struct Policy402.PolicyState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "fileId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "currentVersion",
                  type: "uint256",
                },
              ],
              internalType: "struct Policy402.PolicyState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "getPolicyHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "getPolicyVersion",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "fileId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "version",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "validFrom",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "validUntil",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "paymentAsset",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "payTo",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "enum Policy402.PolicyStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "policyHash",
                  type: "bytes32",
                },
              ],
              internalType: "struct Policy402.PolicyVersionState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicyVersionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "isPolicyValid",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "isPolicyValidAt",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "revokePolicy",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41362255,
      hederaContractId: "0.0.10862565",
    },
  },
  31337: {
    FileRegistry: {
      address: "0x0Ac85d55ebFc7f7b0cF4c13bb3BD6Eaf3909d62d",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "field",
              type: "string",
            },
          ],
          name: "EmptyValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileAlreadyRegistered",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "FileNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidContentHash",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "NotFileOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "FileDelisted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "FileRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "string",
              name: "oldPayToAccountId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "PayToChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "oldPriceTinybar",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "PriceChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "VisibilityChanged",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_PAGE_SIZE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PAYMENT_ASSET",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
          ],
          name: "computeFileId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "delistFile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          name: "getFile",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getFileCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "limit",
              type: "uint256",
            },
          ],
          name: "getFiles",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "ids",
              type: "bytes32[]",
            },
            {
              components: [
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "payToAccountId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isPublic",
                  type: "bool",
                },
                {
                  internalType: "string",
                  name: "objectKey",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "contentHash",
                  type: "bytes32",
                },
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "mimeType",
                  type: "string",
                },
                {
                  internalType: "bool",
                  name: "exists",
                  type: "bool",
                },
              ],
              internalType: "struct FileRegistry.FileItem[]",
              name: "files",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "objectKey",
              type: "string",
            },
            {
              internalType: "string",
              name: "payToAccountId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "contentHash",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "mimeType",
              type: "string",
            },
          ],
          name: "registerFile",
          outputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "newPayToAccountId",
              type: "string",
            },
          ],
          name: "setPayToAccountId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "newPriceTinybar",
              type: "uint256",
            },
          ],
          name: "setPrice",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "fileId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "isPublic",
              type: "bool",
            },
          ],
          name: "setVisibility",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41350056,
    },
    Policy402: {
      address: "0x4B901e2Db7C412D966689E8D3CF479294C456f1e",
      abi: [
        {
          inputs: [],
          name: "InvalidPayTo",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPaymentAsset",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPrice",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidServiceId",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidValidityWindow",
          type: "error",
        },
        {
          inputs: [],
          name: "NotOwner",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyAlreadyExists",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyAlreadyRevoked",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyNotFound",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyVersionNotFound",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "PolicyCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
          ],
          name: "PolicyRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "policyHash",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "PolicyVersionCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "computePolicyHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
          ],
          name: "computePolicyId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "descriptor",
              type: "string",
            },
          ],
          name: "computeServiceId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "createPolicy",
          outputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "validFrom",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "validUntil",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "paymentAsset",
              type: "string",
            },
            {
              internalType: "string",
              name: "payTo",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "priceTinybar",
              type: "uint256",
            },
          ],
          name: "createVersion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "serviceId",
              type: "bytes32",
            },
          ],
          name: "getCurrentPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "currentVersion",
                  type: "uint256",
                },
              ],
              internalType: "struct Policy402.PolicyState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicy",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "currentVersion",
                  type: "uint256",
                },
              ],
              internalType: "struct Policy402.PolicyState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "getPolicyHash",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "getPolicyVersion",
          outputs: [
            {
              components: [
                {
                  internalType: "bytes32",
                  name: "policyId",
                  type: "bytes32",
                },
                {
                  internalType: "bytes32",
                  name: "serviceId",
                  type: "bytes32",
                },
                {
                  internalType: "address",
                  name: "owner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "version",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "validFrom",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "validUntil",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "paymentAsset",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "payTo",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "priceTinybar",
                  type: "uint256",
                },
                {
                  internalType: "enum Policy402.PolicyStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "policyHash",
                  type: "bytes32",
                },
              ],
              internalType: "struct Policy402.PolicyVersionState",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
          ],
          name: "getPolicyVersionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "isPolicyValid",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "isPolicyValidAt",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "policyId",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "version",
              type: "uint256",
            },
          ],
          name: "revokePolicy",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41350058,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
